name: Manually Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        type: choice
        description: image tag to deploy
        required: true
        options: 
        - task-D
        - build-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Send Deploy Notification to Discord
      run: |
        curl \
        -H "Content-Type: application/json" \
        -X POST \
        -d '{"message": "Deploy Approval Request", "actionUrl": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}' \
        ${{ vars.DISCORD_WEBHOOK_URL }}
