name: Manually Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        type: choice
        description: image tag to deploy
        required: true
        options: 
        - task-D
        - build-test

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Send Deploy Approval Request to Discord
      run: |
        curl \
        -H "Content-Type: application/json" \
        -X POST \
        -d '{"content": "Deploy Approval Request: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
        ${{ vars.DISCORD_WEBHOOK_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: discord-notification
    environment: dev
    steps:
    - name: Echo Approval
      run: echo "This is the message after Approval"
