name: task-6-2-apply-after-merge

on:
  push:
    branches: ["task-6-2-D"]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Send Deploy Approval Request to Discord
      run: |
        curl \
        -H "Content-Type: application/json" \
        -X POST \
        -d '{"content": "Apply Approval Request: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
        ${{ vars.DISCORD_WEBHOOK_URL }}

  apply:
    runs-on: ubuntu-latest
    needs: discord-notification
    environment: task-6-2
    defaults:
      run:
        working-directory: task-6-2/src
    steps:
    - uses: actions/checkout@v4

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ vars.TASK_6_2_GITHUB_ACTION_IAM_ARN }}
        aws-region: ap-northeast-1
    
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - id: terraform_plan
      name: Terraform Plan
      run: terraform plan -no-color
