name: task-6-2-apply-after-merge

on:
  push:
    branches: ["task-6-2-D"]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Send Deploy Approval Request to Discord
      run: |
        curl \
        -H "Content-Type: application/json" \
        -X POST \
        -d '{"content": "Apply Approval Request: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
        ${{ vars.DISCORD_WEBHOOK_URL }}

  apply:
    runs-on: ubuntu-latest
    needs: discord-notification
    environment: task-6-2
    outputs:
        instance-id: ${{ steps.terraform_apply.outputs.INSTANCE_ID }}
        instance-public-ip: ${{ steps.terraform_apply.outputs.INSTANCE_PUBLIC_IP }}
    defaults:
      run:
        working-directory: task-6-2/src
    steps:
    - uses: actions/checkout@v4

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ vars.TASK_6_2_GITHUB_ACTION_IAM_ARN }}
        aws-region: ap-northeast-1
    
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -no-color

    - id: terraform_apply
      name: Terraform Apply
      run: |
        terraform apply -auto-approve
        echo "INSTANCE_PUBLIC_IP=$(terraform output -raw instance_public_ip )" >> "$GITHUB_OUTPUT"
        echo "INSTANCE_ID=$(terraform output -raw instance_id)" >> "$GITHUB_OUTPUT"

    - name: Terraform Destroy
      if: failure()
      run: terraform destroy -auto-approve

  ssh-test:
    runs-on: ubuntu-latest
    needs: apply
    steps:
    - run: |
        echo ${{needs.apply.outputs.instance-public-ip}} ${{needs.apply.outputs.instance-id}}
